### PR TITLE
Vet clinic database: database performance audit

### PR DESCRIPTION
**Pull request by ad9311**
# Greetings! 👋🏽 

In this PR we present the following changes:

- Make use of schema.sql and data.sql to create our database. For better readability we have place all the commands in one file, schema.sql
- Take screenshots of all the queries before.
- Add indexes to reduce the excecution time. Indexes are primarily used to enhance database performance.
  - `CREATE INDEX animal_id_index ON visits(animal_id);`
- Take screenshots with the times update

### CODE REVIEW

**Comment by ad9311** [comment]
Before for animal id
before_animal_id
After animal id
after_animal_id

**Comment by ad9311** [comment]
Before vet id
before_vet_id
After vet id
after_vet_id

**Comment by ad9311** [comment]
Before owner's emai
before_email
After owner's email
after_email

**Review by oxenprogrammer — APPROVED** [review]
Hi @ad9311 and @mariordgez, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
